### PR TITLE
add client assertion update callback event

### PR DESCRIPTION
**Pull request by ubik**

### CODE REVIEW

**Comment by leastprivilege** [comment]
Thanks! Will have a look.

**Comment by ubik** [comment]
@leastprivilege How's it going? Perhaps something needs to be fixed or rewritten?

**Comment by leastprivilege** [comment]
Hey, 

sorry - but I was busy. Hopefully next week I will find some time to look at it.

**Comment by leastprivilege** [comment]
Hey

a) could you update the PR to resolve the conflict?
b) maybe this here

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/5053d30c0abdb2aecbd482e31abca8dbf81a2bfd/src/OAuth2IntrospectionOptions.cs#L50

should go away - IOW if you want to use assertions, they must be supplied via the event. Having both event and static config is confusing..what's your opinion?

**Comment by leastprivilege** [comment]
Sorry. you need to update again.

**Comment by ubik** [comment]
done

**Comment by ubik** [comment]
@leastprivilege Is there any chance that request will be merged this week?

**Comment by leastprivilege** [comment]
I will try.

**Comment by leastprivilege** [comment]
Looks good - last thing missing are some test. Could you please add them?

**Comment by ubik** [comment]
> Looks good - last thing missing are some test. Could you please add them?

I have added ActiveToken_With_ClientAssertion test with 2 cases (first request & cache) to test/Tests/Introspection.cs. 
Which cases should be additionally tested?

**Comment by leastprivilege** [comment]
OK - thanks. I think that's sufficient for now.

**Comment by leastprivilege** [comment]
Will push a preview today. Please test it in your real environment and let me know.

**Comment by ubik** [comment]
Ok, thanks

**Pull request merged**
