### PR TITLE
De-deplicate requests for the same token before the cache is populated

### PR DESCRIPTION
**Pull request by ChrisBellew**
There is already an IDistributedCache to hold claims once they have been fetched. But before the cache has been populated there is a window where lots of threads can come in and make network requests for the same token. I have added a keyed semaphore so if many threads want claims for the same token, only one thread is able to make the request while the others wait

### CODE REVIEW

**Comment by ChrisBellew** [comment]
I introduced a bug where if the token failed validation it would try to put null claims in the cache. This is now fixed :)

**Comment by brockallen** [comment]
Is it possible to use a `Lazy` (with `LazyThreadSafetyMode.ExecutionAndPublication`) instead of using a semaphore in this? If so, would that help with simplicity?

Also, then since we need async why not this approach: https://blogs.msdn.microsoft.com/pfxteam/2011/01/15/asynclazyt/?

**Comment by ChrisBellew** [comment]
@brockallen, thanks for the response. 

Good suggestion. Since we need the async initialiser, I have taken the AsyncLazy<T> you posted and used that instead. This should be safe to use as the initialisation function we provide does not perform an await inside it, which is what was causing the deadlocks in [this issue](https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/issues/3). Instead the await is performed on the value that is returned from the AsyncLazy, outside the initialisation lock.

I have replaced KeyedSemaphore and my own LazyAsync with the much simpler AsyncLazy from the [link](https://blogs.msdn.microsoft.com/pfxteam/2011/01/15/asynclazyt/) you provided. The AsyncLazy is now providing de-duplication of the following actions:
- Creation of the introspection client (similar to before).
- Fetching of the claims using the introspection client. After the claims have returned the AsyncLazy is discarded and the claims are placed in the existing cache if necessary.

**Comment by ChrisBellew** [comment]
Is there anything else I can do to help this get pulled? Thanks

**Comment by leastprivilege** [comment]
Maybe do our day jobs ;)

We'll get to it ASAP.

**Comment by brockallen** [comment]
we finally had a look -- thanks!

**Comment by ChrisBellew** [comment]
Thanks!

**Pull request merged**
