### PR TITLE
Allow customization of introspection requests

### PR DESCRIPTION
**Pull request by andrew-laughlin**
This change adds an interface and default implementation, that allows customization of introspection requests. If a custom implementation of the interface is injected (via DI) it is used, otherwise the default request generator is used. This should be a non-breaking change.

### CODE REVIEW

**Comment by andrew-laughlin** [comment]
@leastprivilege let me know if this looks alright, or if there's a different way you'd like to implement this.

**Comment by leastprivilege** [comment]
We will look into it ASAP - super busy right now (and for the next weeks).

**Comment by andrew-laughlin** [comment]
@leastprivilege, @brockallen, hey guys, this is quickly moving up our priority list. Any idea when you'll get an opportunity to take a look?

**Comment by leastprivilege** [comment]
added a couple of comments..

**Comment by andrew-laughlin** [comment]
@leastprivilege thanks for reviewing. For some reason I don't see comments, could you point me to them?

**Comment by leastprivilege** [comment]
Hm - seems the review feature is only for owner...

OK - the main one:

you are essentially turning the generator into a singleton - wouldn't it be better to manually resolve the generator from the container inside the handler? This way the developer can decide on the lifetime of the generator (singleton, transient, scoped).

**Comment by andrew-laughlin** [comment]
@leastprivilege makes sense. I've made an update that resolves the generator inside the handler. Take a look.

**Comment by leastprivilege** [comment]
btw - what are your plans wrt ASP.NET Core 2 ?

**Comment by andrew-laughlin** [comment]
Looks like auth is different in 2.0 (https://github.com/aspnet/Announcements/issues/262). It'll be awhile before we're able to move -- i.e. we'll need this for 1.1. Any suggestions?

**Comment by leastprivilege** [comment]
I am sorry this takes so long - we are both swamped with work and our updates to 2.0

I suggest you go with a private version build for now.

**Comment by leastprivilege** [comment]
We just released 3.0.0 for ASP.NET Core 2 -

we don't have the cycles to continue supporting the old version. If you want to re-consider this feature on top of the new architecture - let me know.

**Comment by andrew-laughlin** [comment]
Yes, it's valuable to have hooks into the introspection process to support customizations.

**Pull request closed without merging**
