### PR TITLE
Remove deadlock opportunities

### PR DESCRIPTION
**Pull request by ChrisBellew**
Replaced System.Lazy with a non-locking lazy wrapper to allow async/await to be used inside the initialisation function without causing deadlocks.

Also added ConfigureAwait(false) to all await calls to avoid deadlocks on continuations.

### CODE REVIEW

**Comment by leastprivilege** [comment]
does not build

**Comment by ChrisBellew** [comment]
Fixed the test. The LazyAsync I replaced instead of the System.Lazy now as an asynchronous value accessor so I synchronously wait. This should be OK because it's inside of the constructor and it's only used in tests

**Comment by ChrisBellew** [comment]
Any feedback on this? Thanks.

**Comment by brockallen** [comment]
Dom's traveling this week.

**Comment by leastprivilege** [comment]
Had a quick look - looks good so far. But I am not an expert on async programming.

Out of interest - why did you not use something like https://blogs.msdn.microsoft.com/pfxteam/2011/01/15/asynclazyt/

**Comment by ChrisBellew** [comment]
Plain didn't know it existed. Good find

**Comment by leastprivilege** [comment]
Wanna update to it?

**Comment by brockallen** [comment]
Thanks!

**Pull request merged**
