### PR TITLE
Support for ASP.NET Core 2

### PR DESCRIPTION
**Pull request by leastprivilege**

### CODE REVIEW

**Comment by leastprivilege** [comment]
things to check:

* in-sync with all the ceremony needed for authN handlers
* weird "deadlock" behavior in tests

**Comment by ThorstenHans** [comment]
Any schedule for merging this PR @leastprivilege @brockallen

**Comment by leastprivilege** [comment]
Sure - check our tests and maybe you can tell me why we sometimes have these delays in there. Once that is solved I am happy to merge ;)

**Comment by ThorstenHans** [comment]
hmm, where does the deadlock appear? Executed tests a couple of times. Both on mac and win / command shell and VS working in all scenarios. At least on my machine 😄 

image

**Comment by leastprivilege** [comment]
Some are very slow and when you step through you'll see the issue.


-------
Dominick Baier

**Comment by ThorstenHans** [comment]
ah I see. will look into those this eve

**Comment by brockallen** [comment]
:shipit:

**Pull request merged**
